# Generated by Django 3.2.2 on 2021-05-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('queue_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('queue_id', models.CharField(default=True, max_length=255)),
                ('room_id', models.CharField(default=True, max_length=255)),
                ('song_id', models.CharField(default=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_list_title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('profile_pic', models.CharField(max_length=1000)),
                ('admin_status', models.BooleanField(default=False)),
                ('ban_status', models.BooleanField(default=False)),
                ('ban_comments', models.CharField(max_length=4195, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.CharField(default=True, max_length=255, primary_key=True, serialize=False)),
                ('room_id', models.CharField(default=True, max_length=20)),
                ('user_id', models.CharField(default=True, max_length=20)),
                ('song_id', models.CharField(default=True, max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='id',
        ),
        migrations.AddField(
            model_name='rooms',
            name='population',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='roomType',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
