# Generated by Django 3.2.2 on 2021-05-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210511_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='queue',
            name='large_song_image_url',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='queue',
            name='small_song_image_url',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='queue',
            name='song_artist',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='queue',
            name='song_duration',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='queue',
            name='song_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='queue',
            name='song_track_url',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
