# Generated by Django 3.2.2 on 2021-05-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_queue_time_added_to_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='room_id',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='song_id',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user_id',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
