# Generated by Django 3.2.2 on 2021-05-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210514_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_song_end_time',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='current_song_track_url',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='current_track_id',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
