# Generated by Django 3.2.2 on 2021-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20210515_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_song_artist',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='current_song_name',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rooms',
            name='current_song_start_time',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
