# Generated by Django 3.2.2 on 2021-05-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210515_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nextsong',
            fields=[
                ('room_id', models.CharField(default=True, max_length=255)),
                ('queue_item_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('time_submitted', models.CharField(default=True, max_length=255)),
                ('room_song_number', models.CharField(default=True, max_length=255)),
                ('song_track_id', models.CharField(default=True, max_length=255)),
                ('song_name', models.CharField(default=True, max_length=255)),
                ('song_artist', models.CharField(default=True, max_length=255)),
                ('song_track_url', models.CharField(default=True, max_length=255)),
                ('small_song_image_url', models.CharField(default=True, max_length=255)),
                ('large_song_image_url', models.CharField(default=True, max_length=255)),
                ('song_duration', models.CharField(default=True, max_length=255)),
            ],
        ),
    ]
