# Generated by Django 3.2.2 on 2021-05-18 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_rooms_room_song_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='current_song_duration',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
