# Generated by Django 3.2.2 on 2021-05-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_rooms_current_song_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=True, max_length=255)),
                ('message', models.CharField(default=True, max_length=255)),
            ],
        ),
    ]
