# Generated by Django 3.2.2 on 2021-05-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextsong',
            name='queue_item_id',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='nextsong',
            name='time_submitted',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
